xkb_rules_layout=us
xkb_rules_options=ctrl:nocaps
repeat_rate=30
repeat_delay=250
numlockon=1
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=1
scroll_method=1
click_method=2
accel_profile=1
accel_speed=0.0
swipe_min_threshold=20
mouse_natural_scrolling=0
button_map=0
drag_corner=4
drag_warp_cursor=1
drag_tile_to_tile=1
enable_floating_snap=1
snap_distance=20
