# Scroller Layout ────────────────────────────────
scroller_structs=10
scroller_default_proportion=0.40
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
scroller_ignore_proportion_single=0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.33,0.67,0.80,1.0


# Dwindle Layout ─────────────────────────────────
new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0
center_master_overspread=1
center_when_single_stack=1


# Overview ───────────────────────────────────────
enable_hotarea=1
hotarea_size=12
hotarea_corner=0
ov_tab_mode=0
overviewgappi=20
overviewgappo=80
