source=~/.config/mango/conf.d/autostart.conf
source=~/.config/mango/conf.d/env.conf
source=~/.config/mango/conf.d/appearance.conf
source=~/.config/mango/conf.d/effects.conf
source=~/.config/mango/conf.d/animations.conf
source=~/.config/mango/conf.d/layouts.conf
source=~/.config/mango/conf.d/misc.conf
source=~/.config/mango/conf.d/monitor.conf
source=~/.config/mango/conf.d/inputs.conf
source=~/.config/mango/conf.d/tags.conf
source=~/.config/mango/conf.d/rules.conf
source=~/.config/mango/conf.d/binds.conf
# This sources the noctalia theme

source = /home/ahsan/.config/mango/noctalia.conf

