# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131316ff
bordercolor = 0x919099ff
focuscolor = 0xc0c2f8ff
maximizescreencolor = 0xc5c4dcff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xefb5ddff
globalcolor = 0x3f4370ff
overlaycolor = 0x444559ff
